#!/usr/bin/env bash
# Validates a commit message (or PR title) against the project's
# Conventional Commits rules. Single source of truth for the local
# commit-msg hook and for CI.
#
# Usage: scripts/lint-commit-msg.sh <file-with-message>
set -euo pipefail

types='feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert'
max_header=72

file=${1:?usage: lint-commit-msg.sh <file-with-message>}

# Drop git's comment lines, keep everything else in order.
mapfile -t lines < <(awk '!/^#/' "$file")
header=${lines[0]:-}

# Generated by git itself; not ours to police.
case "$header" in
  Merge\ * | Revert\ \"* | fixup!\ * | squash!\ * | amend!\ *) exit 0 ;;
esac

errors=()

if [[ ! $header =~ ^($types)(\([a-z0-9][a-z0-9./-]*\))?!?:\ [^[:space:]].*$ ]]; then
  errors+=("header must look like '<type>(<scope>)!: <subject>' with type one of: ${types//|/, }")
else
  subject=${header#*: }
  [[ $subject =~ ^[A-Z][a-z] ]] && errors+=("subject must start in lower case")
  [[ $subject == *. ]] && errors+=("subject must not end with a period")
fi

((${#header} > max_header)) && errors+=("header is ${#header} chars, max is $max_header")

if ((${#lines[@]} > 1)) && [[ -n ${lines[1]} ]]; then
  errors+=("second line must be blank (separates header from body)")
fi

if ((${#errors[@]} > 0)); then
  {
    echo "✖ invalid commit message: $header"
    printf '  - %s\n' "${errors[@]}"
    echo "  see CONTRIBUTING.md#commit-messages"
  } >&2
  exit 1
fi
