//! Source-derived documentation and dependency boundary checks.

use std::{
    collections::BTreeMap,
    fmt::Write as _,
    fs,
    path::{Path, PathBuf},
    process::Command,
};

use anyhow::{Context as _, bail};
use proc_macro2::TokenTree;
use schemars::{JsonSchema, schema_for};
use serde::Deserialize;
use serde_json::Value;

mod file_size;
mod lint_policy;
mod settings_reference;

const GENERATED: &str = "<!-- Generated by cargo xtask docs. Do not edit by hand. -->\n\n";

#[derive(Deserialize)]
struct Metadata {
    packages: Vec<Package>,
}
#[derive(Deserialize)]
struct Package {
    name: String,
    description: Option<String>,
    manifest_path: PathBuf,
    metadata: Value,
    dependencies: Vec<Dependency>,
}
#[derive(Deserialize)]
struct Dependency {
    name: String,
    kind: Option<String>,
}
#[derive(Deserialize)]
struct Keymap {
    section: Vec<Section>,
}
#[derive(Deserialize)]
struct Section {
    context: Option<String>,
    #[serde(default)]
    os: Vec<String>,
    bindings: BTreeMap<String, String>,
}

fn main() -> anyhow::Result<()> {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .context("workspace root")?;
    let arguments: Vec<_> = std::env::args().skip(1).collect();
    match arguments.first().map(String::as_str) {
        Some("docs") => {
            if arguments.iter().skip(1).any(|arg| arg != "--check") {
                bail!("usage: cargo xtask docs [--check]");
            }
            write_docs(root, arguments.iter().any(|arg| arg == "--check"))
        }
        Some("architecture") if arguments.len() == 1 => {
            architecture(root)?;
            lint_policy::check(root)?;
            settings_reference::check(root)?;
            file_size::check(root)
        }
        _ => bail!("usage: cargo xtask docs [--check] | architecture"),
    }
}

fn metadata(root: &Path) -> anyhow::Result<Metadata> {
    let output = Command::new("cargo")
        .args(["metadata", "--no-deps", "--format-version", "1"])
        .current_dir(root)
        .output()?;
    if !output.status.success() {
        bail!(
            "cargo metadata failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );
    }
    Ok(serde_json::from_slice(&output.stdout)?)
}

fn allowed(source: &str, destination: &str) -> bool {
    match source {
        "foundation" => destination == "foundation",
        "domain" => matches!(destination, "domain" | "foundation"),
        "adapter" => matches!(destination, "domain" | "foundation"),
        // Services own GPUI entities but no views: they never reach the UI.
        "service" => matches!(destination, "service" | "domain" | "foundation"),
        "ui" => matches!(destination, "ui" | "domain" | "foundation"),
        "feature" => matches!(destination, "service" | "ui" | "domain" | "foundation"),
        "app" => destination != "tooling",
        // Generated references read every crate's settings sections.
        "tooling" => !matches!(destination, "app" | "tooling"),
        _ => false,
    }
}

fn check_dependency(
    source: &str,
    dependency: &Dependency,
    layers: &BTreeMap<&str, &str>,
) -> anyhow::Result<()> {
    let name = dependency.name.as_str();
    if let Some(destination) = layers.get(name) {
        if !allowed(source, destination) {
            bail!("{source} depends on {name} ({destination})");
        }
    } else if name.starts_with("nocterm-") {
        bail!("internal dependency {name} has no declared architecture layer");
    } else if dependency.kind.as_deref() != Some("dev")
        && matches!(source, "foundation" | "domain" | "adapter")
        && matches!(
            name,
            "gpui" | "gpui-kit" | "gpui-component" | "gpui-pre" | "gpui-base"
        )
    {
        bail!("{source} runtime depends on GUI library {name}");
    } else if dependency.kind.as_deref() != Some("dev")
        && source == "service"
        && matches!(name, "gpui-kit" | "gpui-component")
    {
        bail!("{source} runtime depends on component library {name}");
    }
    Ok(())
}

fn architecture(root: &Path) -> anyhow::Result<String> {
    let mut metadata = metadata(root)?;
    metadata
        .packages
        .sort_by(|left, right| left.name.cmp(&right.name));
    let layers: BTreeMap<_, _> = metadata
        .packages
        .iter()
        .map(|package| {
            let layer = package
                .metadata
                .pointer("/nocterm/layer")
                .and_then(Value::as_str)
                .with_context(|| format!("{} has no architecture layer", package.name))?;
            if !matches!(
                layer,
                "foundation"
                    | "domain"
                    | "adapter"
                    | "service"
                    | "ui"
                    | "feature"
                    | "app"
                    | "tooling"
            ) {
                bail!("{} has unknown layer {layer}", package.name);
            }
            Ok((package.name.as_str(), layer))
        })
        .collect::<anyhow::Result<_>>()?;
    let mut text = format!(
        "{GENERATED}# Architecture dependency map\n\nDerived from Cargo manifests. Check boundaries with `cargo xtask architecture`.\n\n| Crate | Layer | Internal dependencies | Purpose |\n| --- | --- | --- | --- |\n"
    );
    let mut edges = String::new();
    for package in &metadata.packages {
        let source = layers[package.name.as_str()];
        for dependency in &package.dependencies {
            check_dependency(source, dependency, &layers)
                .with_context(|| format!("architecture violation in {}", package.name))?;
        }
        let mut dependencies: Vec<_> = package
            .dependencies
            .iter()
            .filter_map(|dependency| {
                layers
                    .get(dependency.name.as_str())
                    .map(|layer| (dependency.name.as_str(), *layer))
            })
            .collect();
        dependencies.sort_unstable();
        dependencies.dedup();
        for (name, _) in &dependencies {
            writeln!(
                edges,
                "    {} --> {}",
                package.name.replace('-', "_"),
                name.replace('-', "_")
            )?;
        }
        writeln!(
            text,
            "| `{}` | {} | {} | {} |",
            package.name,
            source,
            dependencies
                .iter()
                .map(|(name, _)| format!("`{name}`"))
                .collect::<Vec<_>>()
                .join(", "),
            escape(package.description.as_deref().unwrap_or(""))
        )?;
        if !package.manifest_path.starts_with(root) {
            bail!("workspace member is outside repository");
        }
    }
    write!(text, "\n```mermaid\ngraph TD\n{edges}```\n")?;
    Ok(text)
}

fn escape(value: &str) -> String {
    value.replace('|', "\\|").replace('\n', " ")
}

fn resolve<'a>(schema: &'a Value, root: &'a Value) -> &'a Value {
    if let Some(reference) = schema
        .get("$ref")
        .and_then(Value::as_str)
        .and_then(|reference| reference.strip_prefix('#'))
    {
        root.pointer(reference).unwrap_or(schema)
    } else {
        schema
    }
}

pub(crate) fn schema_rows(
    schema: &Value,
    root: &Value,
    defaults: &Value,
    prefix: &str,
    text: &mut String,
) -> anyhow::Result<()> {
    let schema = resolve(schema, root);
    if let Some(properties) = schema.get("properties").and_then(Value::as_object) {
        // Sorted by name whether or not serde_json preserves insertion order.
        let properties: BTreeMap<_, _> = properties.iter().collect();
        for (name, child) in properties {
            let path = if prefix.is_empty() {
                name.clone()
            } else {
                format!("{prefix}.{name}")
            };
            schema_rows(
                child,
                root,
                defaults.get(name).unwrap_or(&Value::Null),
                &path,
                text,
            )?;
        }
    } else {
        let description = schema
            .get("description")
            .and_then(Value::as_str)
            .unwrap_or("");
        let mut resolved = schema;
        if let Some(variants) = schema.get("anyOf").and_then(Value::as_array) {
            resolved = variants
                .iter()
                .find(|variant| variant.get("type").and_then(Value::as_str) != Some("null"))
                .map(|variant| resolve(variant, root))
                .unwrap_or(schema);
        }
        let choices = resolved
            .get("oneOf")
            .and_then(Value::as_array)
            .map(|variants| {
                variants
                    .iter()
                    .flat_map(|variant| {
                        if let Some(value) = variant.get("const") {
                            vec![value.to_string()]
                        } else {
                            variant
                                .get("enum")
                                .and_then(Value::as_array)
                                .cloned()
                                .unwrap_or_default()
                                .iter()
                                .map(Value::to_string)
                                .collect()
                        }
                    })
                    .collect::<Vec<_>>()
            });
        let mut kind = choices
            .filter(|choices| !choices.is_empty())
            .map(|choices| choices.join(", "))
            .or_else(|| resolved.get("enum").map(Value::to_string))
            .or_else(|| resolved.get("type").map(Value::to_string))
            .unwrap_or_else(|| "object".into());
        if let (Some(minimum), Some(maximum)) = (schema.get("minimum"), schema.get("maximum")) {
            write!(kind, "; {minimum}–{maximum}")?;
        }
        writeln!(
            text,
            "| `{prefix}` | {} | `{}` | {} |",
            escape(&kind),
            escape(&defaults.to_string()),
            escape(description)
        )?;
    }
    Ok(())
}

fn reference<T: JsonSchema>(title: &str, defaults: Value) -> anyhow::Result<String> {
    let mut text = reference_header(title);
    let schema = serde_json::to_value(schema_for!(T))?;
    schema_rows(&schema, &schema, &defaults, "", &mut text)?;
    Ok(text)
}

pub(crate) fn reference_header(title: &str) -> String {
    format!(
        "{GENERATED}# {title}\n\n`null` means the value is inherited or unset. Dictionaries are shown as objects.\n\n| Key | Type / choices | Default | Description |\n| --- | --- | --- | --- |\n"
    )
}

pub(crate) fn source_files(directory: &Path, files: &mut Vec<PathBuf>) -> anyhow::Result<()> {
    for entry in fs::read_dir(directory)? {
        let path = entry?.path();
        if path.is_dir() {
            source_files(&path, files)?;
        } else if path.extension().is_some_and(|extension| extension == "rs") {
            files.push(path);
        }
    }
    files.sort();
    Ok(())
}

fn action_declarations(source: &str) -> anyhow::Result<BTreeMap<String, String>> {
    let mut actions = BTreeMap::new();
    for item in syn::parse_file(source)?.items {
        let syn::Item::Macro(item) = item else {
            continue;
        };
        if !item
            .mac
            .path
            .segments
            .last()
            .is_some_and(|segment| segment.ident == "actions")
        {
            continue;
        }
        let mut tokens = item.mac.tokens.into_iter();
        let Some(TokenTree::Ident(namespace)) = tokens.next() else {
            bail!("action namespace must be an identifier");
        };
        let Some(TokenTree::Punct(_)) = tokens.next() else {
            bail!("expected action namespace separator");
        };
        let Some(TokenTree::Group(group)) = tokens.next() else {
            bail!("expected actions list");
        };
        let mut description = Vec::new();
        for token in group.stream() {
            match token {
                TokenTree::Group(group) if group.delimiter() == proc_macro2::Delimiter::Bracket => {
                    let attribute = group.stream().to_string();
                    if let Some(literal) = attribute.strip_prefix("doc = ") {
                        description.push(
                            syn::parse_str::<syn::LitStr>(literal)?
                                .value()
                                .trim()
                                .to_owned(),
                        );
                    }
                }
                TokenTree::Ident(name) => {
                    actions.insert(format!("{namespace}::{name}"), description.join(" "));
                    description.clear();
                }
                _ => {}
            }
        }
    }
    Ok(actions)
}

fn actions(root: &Path) -> anyhow::Result<String> {
    let mut files = Vec::new();
    source_files(&root.join("crates"), &mut files)?;
    let mut declarations = BTreeMap::new();
    for file in files {
        for (name, description) in action_declarations(&fs::read_to_string(file)?)? {
            if declarations.insert(name.clone(), description).is_some() {
                bail!("duplicate action {name}");
            }
        }
    }
    let keymap: Keymap = toml::from_str(&fs::read_to_string(root.join("assets/keymap.toml"))?)?;
    let mut bindings: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for section in keymap.section {
        for (keys, action) in section.bindings {
            if !declarations.contains_key(&action) {
                bail!("keymap references undeclared action {action}");
            }
            let platform = if section.os.is_empty() {
                "all".into()
            } else {
                section.os.join(", ")
            };
            bindings.entry(action).or_default().push(format!(
                "`{keys}` ({platform}; {})",
                section.context.as_deref().unwrap_or("global")
            ));
        }
    }
    let mut text = format!(
        "{GENERATED}# Actions and default key bindings\n\nDerived from `actions!` declarations and `assets/keymap.toml`.\n\n| Action | Description | Bindings |\n| --- | --- | --- |\n"
    );
    for (name, description) in declarations {
        writeln!(
            text,
            "| `{name}` | {} | {} |",
            escape(&description),
            escape(&bindings.remove(&name).unwrap_or_default().join("; "))
        )?;
    }
    Ok(text)
}

fn write_docs(root: &Path, check: bool) -> anyhow::Result<()> {
    let documents = [
        ("docs/reference/settings.md", settings_reference::render()?),
        (
            "docs/reference/design-tokens.md",
            reference::<nocterm_design::DesignTokens>(
                "Design tokens",
                serde_json::to_value(nocterm_design::DesignTokens::builtin())?,
            )?,
        ),
        ("docs/reference/actions.md", actions(root)?),
        ("docs/architecture/dependencies.md", architecture(root)?),
    ];
    let mut stale = Vec::new();
    for (name, text) in documents {
        let path = root.join(name);
        if check {
            if fs::read_to_string(&path).ok().as_deref() != Some(&text) {
                stale.push(name);
            }
        } else {
            fs::create_dir_all(path.parent().context("document directory")?)?;
            fs::write(path, text)?;
        }
    }
    if !stale.is_empty() {
        bail!(
            "generated documentation is stale: {}. Run cargo xtask docs",
            stale.join(", ")
        );
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn external_gui_and_undeclared_internal_dependencies_cannot_escape_the_policy() {
        let layers = BTreeMap::from([("nocterm-core", "foundation")]);
        for source in ["foundation", "domain", "adapter"] {
            for kind in [None, Some("build")] {
                let dependency = Dependency {
                    name: "gpui-kit".into(),
                    kind: kind.map(str::to_owned),
                };
                assert!(check_dependency(source, &dependency, &layers).is_err());
            }
        }
        let test_support = Dependency {
            name: "gpui-kit".into(),
            kind: Some("dev".into()),
        };
        assert!(check_dependency("domain", &test_support, &layers).is_ok());
        let runtime = Dependency {
            name: "gpui-kit".into(),
            kind: None,
        };
        assert!(check_dependency("ui", &runtime, &layers).is_ok());
        assert!(check_dependency("service", &runtime, &layers).is_err());
        let gpui = Dependency {
            name: "gpui-pre".into(),
            kind: None,
        };
        assert!(check_dependency("service", &gpui, &layers).is_ok());
        let missing = Dependency {
            name: "nocterm-forgotten".into(),
            kind: None,
        };
        assert!(check_dependency("app", &missing, &layers).is_err());
    }
    #[test]
    fn feature_and_transport_boundaries_are_enforced() {
        assert!(!allowed("feature", "feature"));
        assert!(allowed("feature", "service"));
        assert!(!allowed("service", "ui"));
        assert!(!allowed("service", "feature"));
        assert!(!allowed("feature", "adapter"));
        assert!(!allowed("ui", "feature"));
        assert!(allowed("adapter", "domain"));
        assert!(allowed("app", "feature"));
        assert!(allowed("tooling", "feature"));
        assert!(!allowed("tooling", "app"));
    }
    #[test]
    fn action_parser_reads_namespaces_and_doc_attributes() {
        let actions = action_declarations("gpui_kit::actions!(example, [ /// First command.\n First, /// Second command.\n Second, ]);").unwrap();
        assert_eq!(actions.get("example::First").unwrap(), "First command.");
        assert_eq!(actions.get("example::Second").unwrap(), "Second command.");
    }
}
